CREATE TABLE [dbo].[SDR_Spells] (
    [index]                               NVARCHAR (50)   NOT NULL,
    [name]                                NVARCHAR (50)   NOT NULL,
    [desc]                                NVARCHAR (3850) NOT NULL,
    [higher_level]                        NVARCHAR (450)  NULL,
    [range]                               NVARCHAR (50)   NOT NULL,
    [components]                          NVARCHAR (50)   NOT NULL,
    [material]                            NVARCHAR (350)  NULL,
    [ritual]                              BIT             NOT NULL,
    [duration]                            NVARCHAR (50)   NOT NULL,
    [concentration]                       BIT             NOT NULL,
    [casting_time]                        NVARCHAR (50)   NOT NULL,
    [level]                               TINYINT         NOT NULL,
    [attack_type]                         NVARCHAR (50)   NULL,
    [classes]                             NVARCHAR (100)  NOT NULL,
    [damage_damage_type_name]             NVARCHAR (50)   NULL,
    [damage_damage_at_slot_level_1]       NVARCHAR (50)   NULL,
    [damage_damage_at_slot_level_2]       NVARCHAR (50)   NULL,
    [damage_damage_at_slot_level_3]       NVARCHAR (50)   NULL,
    [damage_damage_at_slot_level_4]       NVARCHAR (50)   NULL,
    [damage_damage_at_slot_level_5]       NVARCHAR (50)   NULL,
    [damage_damage_at_slot_level_6]       NVARCHAR (50)   NULL,
    [damage_damage_at_slot_level_7]       NVARCHAR (50)   NULL,
    [damage_damage_at_slot_level_8]       NVARCHAR (50)   NULL,
    [damage_damage_at_slot_level_9]       NVARCHAR (50)   NULL,
    [damage_damage_at_character_level_1]  TIME (7)        NULL,
    [damage_damage_at_character_level_5]  TIME (7)        NULL,
    [damage_damage_at_character_level_11] TIME (7)        NULL,
    [damage_damage_at_character_level_17] TIME (7)        NULL,
    [heal_at_slot_level_1]                NVARCHAR (50)   NULL,
    [heal_at_slot_level_2]                NVARCHAR (50)   NULL,
    [heal_at_slot_level_3]                NVARCHAR (50)   NULL,
    [heal_at_slot_level_4]                NVARCHAR (50)   NULL,
    [heal_at_slot_level_5]                NVARCHAR (50)   NULL,
    [heal_at_slot_level_6]                NVARCHAR (50)   NULL,
    [heal_at_slot_level_7]                NVARCHAR (50)   NULL,
    [heal_at_slot_level_8]                NVARCHAR (50)   NULL,
    [heal_at_slot_level_9]                NVARCHAR (50)   NULL,
    [area_of_effect_type]                 NVARCHAR (50)   NULL,
    [area_of_effect_size]                 FLOAT (53)      NULL,
    [school_name]                         NVARCHAR (50)   NOT NULL,
    [dc_dc_type_index]                    NVARCHAR (50)   NULL,
    [dc_dc_type_name]                     NVARCHAR (50)   NULL,
    [dc_dc_success]                       NVARCHAR (50)   NULL,
    [dc_desc]                             NVARCHAR (800)  NULL
);

